default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: end-of-file-fixer
      - id: check-ast
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-crlf
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ "--line-length=100" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    # TODO: Switch to a new version as soon as the bug (with Pydantic integration) will be fixed:
    #  https://github.com/pydantic/pydantic/issues/5192
    rev: v1.0.1
    hooks:
      - id: mypy
        # use 'mypy "$@" || true' to ignore exit code
        entry: bash -c 'mypy "$@"' --
        args: [ "--no-strict-optional", "--ignore-missing-imports" ]
        additional_dependencies:
          - pydantic
          - types-redis
